networks:
  podcat-net:

volumes:
  podcat-db-volume:

services:
  podcat-db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: podcat-dev
      MONGO_INITDB_ROOT_PASSWORD: podcat-dev
    ports:
      - 27017:27017
    volumes:
      - podcat-db-volume:/etc/mongo
    networks:
      - podcat-net

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: podcat-dev
      ME_CONFIG_MONGODB_ADMINPASSWORD: podcat-dev
      ME_CONFIG_MONGODB_URL: mongodb://podcat-dev:podcat-dev@podcat-db:27017/
    networks:
      - podcat-net