# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Podcat Core CI/CD

on:
  push:
    branches: [ main, next ]
  pull_request:
    branches: [ main, next ]

jobs:
  format-build-test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 17.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      
      - name: Install dependencies
        run: yarn
      
      - name: Format code
        run: yarn format
      
      - name: Lint code
        run: yarn lint
      
      - name: Build
        run: yarn build
      
      - name: Test
        run: yarn test